package transfers;

public interface TypeRequestAnswer {
    String ERROR = "ERROR";
    String AUTHORIZATION_DONE = "AUTHORIZATION_DONE";
    String AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE";
    String USER_NOT_EXIST = "USER_NOT_EXIST";
    String WRONG_PASSWORD = "WRONG_PASSWORD";
    String REGISTRATION_DONE = "REGISTRATION_DONE";
    String USER_ALREADY_EXIST = "USER_ALREADY_EXIST";
    String BAD_LOGIN = "BAD_LOGIN";
    String BAD_PASSWORD = "BAD_PASSWORD";
    String UPDATE_TOKEN = "UPDATE_TOKEN";
    String NEED_LOGIN = "NEED_LOGIN";
}
